### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'anomaly_video/gepc-master/data/pose/pose_meta_test_length8_stride2.json'

### ISSUE THREAD

**Issue by yanglixin123** [Yui010206/MoPRL#1]
这个文件是从哪儿来？我直接下载公开数据集，运行还是会出现这个报错怎么回事？train的这个文件不是在运行这个命令的时候生成的么？ python train_test.py --exp_name ShanghaiTech_AlphaPose_train --dataset ShanghaiTech_AlphaPose

**Comment by Yui010206** [comment]
Hi 你好 请问可以提供更具体的运行报错截图吗？谢谢！

**Comment by yanglixin123** [comment]
你好，这个问题我解决了！
